id: IPv4 extraction test
version: -1
name: IPv4 extraction test
description: Test extraction flow of IPv4 in XSOAR.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6b54bcd9-b93e-41d4-8aa6-0ce7032a2749
    type: start
    task:
      id: 6b54bcd9-b93e-41d4-8aa6-0ce7032a2749
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: a626b47d-2d52-4ecb-8318-25944fdf4898
    type: regular
    task:
      id: a626b47d-2d52-4ecb-8318-25944fdf4898
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "34"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "34":
    id: "34"
    taskid: 09bf2f48-2098-42f5-8b08-9d7a452685d2
    type: title
    task:
      id: 09bf2f48-2098-42f5-8b08-9d7a452685d2
      version: -1
      name: IP
      description: IP
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "35":
    id: "35"
    taskid: ec2e66a1-f549-430f-80ce-3256a0033637
    type: regular
    task:
      id: ec2e66a1-f549-430f-80ce-3256a0033637
      version: -1
      name: Set valid IPs
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "36"
    scriptarguments:
      key:
        simple: valid_ips
      value:
        simple: '"192.168.1.1", "0[.]0[.]0[.]0","192.168.1.2/test","This is an IP 192.168.1.3. "'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "36":
    id: "36"
    taskid: 254629a2-a63e-4064-8945-82f15145da40
    type: regular
    task:
      id: 254629a2-a63e-4064-8945-82f15145da40
      version: -1
      name: Print valid IPs
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "37"
      - "66"
      - "68"
      - "69"
    scriptarguments:
      value:
        simple: ${valid_ips}
    reputationcalc: 2
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "37":
    id: "37"
    taskid: 6309ff4b-3adb-4599-8a7b-f7887c4d2b35
    type: condition
    task:
      id: 6309ff4b-3adb-4599-8a7b-f7887c4d2b35
      version: -1
      name: Check refanged IP - 0.0.0.0
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "38"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 0.0.0.0
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "38":
    id: "38"
    taskid: decbad18-71a3-4b3f-83d7-ad640341558b
    type: regular
    task:
      id: decbad18-71a3-4b3f-83d7-ad640341558b
      version: -1
      name: Set invalid IPs
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "39"
    scriptarguments:
      key:
        simple: invalid_ips
      value:
        simple: '"192.168","256.1.1.1",1.1.192.168.1.11.1.1.1.1"'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "39":
    id: "39"
    taskid: 40924449-ec3b-47e3-855f-94a9da1f64e7
    type: regular
    task:
      id: 40924449-ec3b-47e3-855f-94a9da1f64e7
      version: -1
      name: Print invalid IPs
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "40"
      - "67"
      - "70"
    scriptarguments:
      value:
        simple: ${invalid_ips}
    reputationcalc: 2
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "40":
    id: "40"
    taskid: 5cd732fc-7cfc-4f06-8506-61e9bd709cc3
    type: condition
    task:
      id: 5cd732fc-7cfc-4f06-8506-61e9bd709cc3
      version: -1
      name: Check non extraction of incomplete IP (192.1688)
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "65"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: notContainsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: "192.168"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "65":
    id: "65"
    taskid: 92329acf-25a7-4a19-82ee-f2ed63cd3b02
    type: regular
    task:
      id: 92329acf-25a7-4a19-82ee-f2ed63cd3b02
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "66":
    id: "66"
    taskid: f5762133-59c7-43a9-8ab4-58e6ce6d1928
    type: condition
    task:
      id: f5762133-59c7-43a9-8ab4-58e6ce6d1928
      version: -1
      name: Check normal IP - 192.168.1.1
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "38"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 192.168.1.1
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "67":
    id: "67"
    taskid: 8e9f812b-8ca2-46c6-86c1-55cb023d5694
    type: condition
    task:
      id: 8e9f812b-8ca2-46c6-86c1-55cb023d5694
      version: -1
      name: Check non extraction of invalid octet
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "65"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: notContainsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 256.1.1.1
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "68":
    id: "68"
    taskid: b73b2b96-a293-49a1-83cd-4119b698abe0
    type: condition
    task:
      id: b73b2b96-a293-49a1-83cd-4119b698abe0
      version: -1
      name: Check IP from url - 192.168.1.2
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "38"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 192.168.1.2
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "69":
    id: "69"
    taskid: 8d30d156-05fb-4f93-8196-b08d5b02f505
    type: condition
    task:
      id: 8d30d156-05fb-4f93-8196-b08d5b02f505
      version: -1
      name: Check IP from free text ending with a dot - 192.168.1.3
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "38"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 192.168.1.3
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "70":
    id: "70"
    taskid: 7f11fba6-256d-4753-86fa-36f62fbb2a11
    type: condition
    task:
      id: 7f11fba6-256d-4753-86fa-36f62fbb2a11
      version: -1
      name: Check non extraction of 192.168.1.11
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "65"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: notContainsGeneral
          left:
            value:
              simple: ${IP.Address}
            iscontext: true
          right:
            value:
              simple: 192.168.1.11
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: Indicators reputation-.json Test
fromversion: 6.5.0
