id: Autofocus Query Samples, Sessions and Tags Test Playbook
version: -1
name: Autofocus Query Samples, Sessions and Tags Test Playbook
fromversion: 5.0.0
description: |-
  This is a test playbook to the the functionality of the Autofocus Query
  Samples and Sessions playbook. The test playbook checks for Autofocus query inputs,
  Direct queries for IP and also tag searches.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1d79a656-8442-4171-89c4-ae253c769434
    type: start
    task:
      id: 1d79a656-8442-4171-89c4-ae253c769434
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 470,
          "y": -90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9a90ebd2-97bc-414d-86bb-da2da08c6d97
    type: playbook
    task:
      id: 9a90ebd2-97bc-414d-86bb-da2da08c6d97
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Commodity:
        simple: "false"
      IP:
        simple: 54.215.248.188,52.8.161.117
      Scope:
        simple: Global
      Search Type:
        simple: all
      Tags class:
        simple: Exploit
      Tags private:
        simple: "false"
      Tags public:
        simple: "True"
      Tags scope:
        simple: all
      Unit 42:
        simple: "false"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 270,
          "y": 215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 6386c645-907c-4247-81b7-2adc15aec524
    type: title
    task:
      id: 6386c645-907c-4247-81b7-2adc15aec524
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 490,
          "y": 620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 9aafe622-4188-4d1d-8707-c7476fdfa256
    type: condition
    task:
      id: 9aafe622-4188-4d1d-8707-c7476fdfa256
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 82b92959-c002-409e-8df3-b3d1609c75f8
    type: title
    task:
      id: 82b92959-c002-409e-8df3-b3d1609c75f8
      version: -1
      name: Test IP and tags input
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: f00513b7-c9e3-48ef-83c5-a26c497dad77
    type: playbook
    task:
      id: f00513b7-c9e3-48ef-83c5-a26c497dad77
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Scope:
        simple: Global
      Search Type:
        simple: session
      SessionQuery:
        complex:
          root: inputs.SessionQuery
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 680,
          "y": 215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 901a25e1-024d-4827-8c89-f52c743bb979
    type: condition
    task:
      id: 901a25e1-024d-4827-8c89-f52c743bb979
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 680,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: d9cfebde-2cfc-4f04-8f35-b21171299f5b
    type: title
    task:
      id: d9cfebde-2cfc-4f04-8f35-b21171299f5b
      version: -1
      name: Test Query input
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 680,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_2_yes": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 775,
        "width": 790,
        "x": 270,
        "y": -90
      }
    }
  }
inputs:
- key: Scope
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: SampleQuery
  value:
    simple: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery: null
- key: SessionQuery
  value:
    simple: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery: null
outputs:
- contextPath: AutoFocus.SessionsResults
  type: string
- contextPath: AutoFocus.SamplesResults
  type: string
- contextPath: AutoFocus.TopTagResults
  type: unknown
