id: Autofocus Query Samples, Sessions and Tags Test Playbook
version: -1
name: Autofocus Query Samples, Sessions and Tags Test Playbook
fromversion: 5.0.0
description: |-
  This is a test playbook to the the functionality of the Autofocus Query
  Samples and Sessions playbook. The test playbook checks for Autofocus query inputs,
  Direct queries for IP and also tag searches.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e1102d9c-2996-43dc-848d-c2f15d0f081a
    type: start
    task:
      id: e1102d9c-2996-43dc-848d-c2f15d0f081a
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: b81cc9f3-905a-41b1-8e28-440bdf6c6f06
    type: playbook
    task:
      id: b81cc9f3-905a-41b1-8e28-440bdf6c6f06
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Commodity:
        simple: "false"
      IP:
        simple: 54.215.248.188,52.8.161.117
      Scope:
        simple: Global
      Search Type:
        simple: all
      Tags class:
        simple: Exploit
      Tags private:
        simple: "false"
      Tags public:
        simple: "True"
      Tags scope:
        simple: all
      Unit 42:
        simple: "false"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e634bb6b-3997-47e4-8350-bc62150f83cc
    type: title
    task:
      id: e634bb6b-3997-47e4-8350-bc62150f83cc
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 77d155fa-d48d-4364-8078-d8efe0165191
    type: condition
    task:
      id: 77d155fa-d48d-4364-8078-d8efe0165191
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 49762ed8-e0f2-4b9b-8855-e44dcd612620
    type: title
    task:
      id: 49762ed8-e0f2-4b9b-8855-e44dcd612620
      version: -1
      name: Test IP and tags input
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 48cc1f35-5eb4-43bb-8fe3-ad02aa6d31f0
    type: playbook
    task:
      id: 48cc1f35-5eb4-43bb-8fe3-ad02aa6d31f0
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Scope:
        simple: Global
      Search Type:
        simple: session
      SessionQuery:
        complex:
          root: inputs.SessionQuery
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 1fef62e2-a280-417f-8d39-41ba43bbb83c
    type: condition
    task:
      id: 1fef62e2-a280-417f-8d39-41ba43bbb83c
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 445c6354-aa15-4d5b-8ded-269537709817
    type: title
    task:
      id: 445c6354-aa15-4d5b-8ded-269537709817
      version: -1
      name: Test Query input
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1200,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Scope
  value: {}
  required: false
  description: ""
  playbookInputQuery:
- key: SampleQuery
  value:
    simple: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery:
- key: SessionQuery
  value:
    simple: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery:
outputs:
- contextPath: AutoFocus.SessionsResults
  type: string
- contextPath: AutoFocus.SamplesResults
  type: string
- contextPath: AutoFocus.TopTagResults
  type: unknown
