id: Autofocus Query Samples, Sessions and Tags Test Playbook
version: -1
name: Autofocus Query Samples, Sessions and Tags Test Playbook
fromversion: 5.0.0
description: |-
  This is a test playbook to the the functionality of the Autofocus Query
  Samples and Sessions playbook. The test playbook checks for Autofocus query inputs,
  Direct queries for IP and also tag searches.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 05a7cb53-fca3-46d1-8e34-2b03ee732ef8
    type: start
    task:
      id: 05a7cb53-fca3-46d1-8e34-2b03ee732ef8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: f5a5761f-8688-495e-89e3-96321fbc2064
    type: playbook
    task:
      id: f5a5761f-8688-495e-89e3-96321fbc2064
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Commodity:
        simple: "false"
      IP:
        simple: 54.215.248.188,52.8.161.117
      Scope:
        simple: Global
      Search Type:
        simple: all
      Tags class:
        simple: Exploit
      Tags private:
        simple: "false"
      Tags public:
        simple: "True"
      Tags scope:
        simple: all
      Unit 42:
        simple: "false"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e99b55c8-806e-4dee-8e07-8ed28b05fe63
    type: title
    task:
      id: e99b55c8-806e-4dee-8e07-8ed28b05fe63
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d98c84bf-6ea6-489f-8d1b-fd08c3d5ebe0
    type: condition
    task:
      id: d98c84bf-6ea6-489f-8d1b-fd08c3d5ebe0
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: aa07e84d-4817-4ade-8af5-7af36ec52fe7
    type: title
    task:
      id: aa07e84d-4817-4ade-8af5-7af36ec52fe7
      version: -1
      name: Test IP and tags input
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 355
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 22f01ae4-d512-4bc0-8271-7c9bd598b7d8
    type: playbook
    task:
      id: 22f01ae4-d512-4bc0-8271-7c9bd598b7d8
      version: -1
      name: Autofocus Query Samples and Sessions
      description: |-
        This playbook is used for querying the PANW threat intelligence Autofocus system. The playbook accepts indicators such as IP's, hashes, domains to run basic queries or mode advanced queries that can leverage several query parameters. In order to run the more advanced queries its recommended to use the Autofocus UI https://autofocus.paloaltonetworks.com/#/dashboard/organization to created a query and than use the export search button. The result can be used as a playbook input.

        The playbook supports searching both the Samples API and the sessions API.
      playbookName: Autofocus Query Samples, Sessions and Tags
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Scope:
        simple: Global
      Search Type:
        simple: session
      SessionQuery:
        complex:
          root: inputs.SessionQuery
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 9ca1720c-7462-4f05-8bad-8d25f582efe3
    type: condition
    task:
      id: 9ca1720c-7462-4f05-8bad-8d25f582efe3
      version: -1
      name: Got Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SessionsResults
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              complex:
                root: AutoFocus
                accessor: SamplesResults
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: b1521221-197a-4137-8e98-f191e2001d4c
    type: title
    task:
      id: b1521221-197a-4137-8e98-f191e2001d4c
      version: -1
      name: Test Query input
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 9e782470-7695-4b9a-8fa7-796f369814cc
    type: regular
    task:
      id: 9e782470-7695-4b9a-8fa7-796f369814cc
      version: -1
      name: Sleep
      description: Sleep for X seconds.
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      seconds:
        simple: "120"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_2_yes": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Scope
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: SampleQuery
  value:
    simple: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"sample.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"sample.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery: null
- key: SessionQuery
  value:
    simple: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  required: false
  description: '{"operator":"any","children":[{"field":"session.sha256","operator":"is","value":"4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0"},{"field":"session.sha256","operator":"is","value":"7e93723c0c34ef98444e5ce9013fef220975b96291a79053fd4c9b3d3550aeb3"}]}'
  playbookInputQuery: null
outputs:
- contextPath: AutoFocus.SessionsResults
  type: string
- contextPath: AutoFocus.SamplesResults
  type: string
- contextPath: AutoFocus.TopTagResults
  type: unknown
