commonfields:
  id: c2315777-c63f-44ac-82f6-9b5395dd96d7
  version: 5
name: valid_automation
script: |+
  """This is a valid_automation
  """

  from typing import Dict, Any
  import traceback

  ''' STANDALONE FUNCTION '''

  def basescript_dummy(dummy: str) -> Dict[str, str]:
      """Returns a simple python dict with the information provided
      in the input (dummy).
      :type dummy: ``str``
      :param dummy: string to add in the dummy dict that is returned
      :return: dict as {"dummy": dummy}
      :rtype: ``str``
      """

      return {"dummy": dummy}

  ''' COMMAND FUNCTION '''

  def basescript_dummy_command(args: Dict[str, Any]) -> CommandResults:

      dummy = args.get('dummy', 'example dummy')

      if not dummy:
          raise ValueError('dummy not specified')

      # Call the standalone function and get the raw response
      result = basescript_dummy(dummy)

      return CommandResults(
          outputs_prefix='BaseScript',
          outputs_key_field='',
          outputs=result,
      )

  ''' MAIN FUNCTION '''

  def main():
      try:
          hello =  'hello'
          # TODO: replace the invoked command function with yours
          return_results(basescript_dummy_command(demisto.args()))
      except Exception as ex:
          demisto.error(traceback.format_exc())  # print the traceback
          return_error(f'Failed to execute BaseScript. Error: {str(ex)}')

  ''' ENTRY POINT '''

  if __name__ in ('__main__', '__builtin__', 'builtins'):
      main()

type: python
tags: []
enabled: true
scripttarget: 0
subtype: python3
pswd: ""
runas: DBotWeakRole
engineinfo: {}
mainengineinfo: {}
