id: Rasterize Test URL
version: -1
name: Rasterize Test URL
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 288c85f5-2c97-491d-895b-02c16e3a63a8
    type: start
    task:
      id: 288c85f5-2c97-491d-895b-02c16e3a63a8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "23"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: fb1730b9-2c11-481d-8d87-df10a6762a1b
    type: title
    task:
      id: fb1730b9-2c11-481d-8d87-df10a6762a1b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 593a33ea-2052-4c03-8382-49b1f6bb4c54
    type: regular
    task:
      id: 593a33ea-2052-4c03-8382-49b1f6bb4c54
      version: -1
      name: 'Rasterize URL -  Full_Screen '
      description: Rasterize a URL into image or PDF
      script: Rasterize|||rasterize
      type: regular
      iscommand: true
      brand: Rasterize
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      full_screen:
        simple: "True"
      type:
        simple: png
      url:
        simple: https://www.google.com
      wait_time:
        simple: "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 6328f002-441f-4f17-806d-141f806b6d8f
    type: regular
    task:
      id: 6328f002-441f-4f17-806d-141f806b6d8f
      version: -1
      name: Test Image (ImageOCR)
      description: Extracts text from an image.
      script: Image OCR|||image-ocr-extract-text
      type: regular
      iscommand: true
      brand: Image OCR
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      entryid:
        complex:
          root: InfoFile
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: InfoFile.Info
                iscontext: true
              right:
                value:
                  simple: image/png
              ignorecase: true
            - operator: isEqualString
              left:
                value:
                  simple: InfoFile.Info
                iscontext: true
              right:
                value:
                  simple: url.png
              ignorecase: true
          accessor: EntryID
          transformers:
          - operator: uniq
          - operator: FirstArrayElement
      execution-timeout:
        simple: "600"
      retry-count:
        simple: "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 60311b38-5427-4c49-8de5-b3e6d617f300
    type: condition
    task:
      id: 60311b38-5427-4c49-8de5-b3e6d617f300
      version: -1
      name: Check Text
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "27"
      "Yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: containsString
          left:
            value:
              complex:
                root: File
                accessor: Text
                transformers:
                - operator: toLowerCase
            iscontext: true
          right:
            value:
              simple: wikipedia
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 3ad1ccec-6591-431a-8119-b75de464afa8
    type: regular
    task:
      id: 3ad1ccec-6591-431a-8119-b75de464afa8
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 1ff3e88d-7296-4a6f-8d30-84227d094cd7
    type: regular
    task:
      id: 1ff3e88d-7296-4a6f-8d30-84227d094cd7
      version: -1
      name: Error Text Validation
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Full-screen image not verified
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "28":
    id: "28"
    taskid: 63365641-60f9-4b7c-849e-2c559cb5fa1c
    type: regular
    task:
      id: 63365641-60f9-4b7c-849e-2c559cb5fa1c
      version: -1
      name: Rasterize URL - Include URL bar
      description: Rasterize a URL into image or PDF
      script: Rasterize|||rasterize
      type: regular
      iscommand: true
      brand: Rasterize
    nexttasks:
      '#none#':
      - "29"
    scriptarguments:
      include_url:
        simple: "True"
      type:
        simple: png
      url:
        simple: https://google.com
      wait_time:
        simple: "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "29":
    id: "29"
    taskid: cd6a1804-fe08-4944-88ed-352b85f792f7
    type: regular
    task:
      id: cd6a1804-fe08-4944-88ed-352b85f792f7
      version: -1
      name: Test Image (ImageOCR)
      description: Extracts text from an image.
      script: Image OCR|||image-ocr-extract-text
      type: regular
      iscommand: true
      brand: Image OCR
    nexttasks:
      '#none#':
      - "30"
    scriptarguments:
      entryid:
        complex:
          root: InfoFile
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: InfoFile.Info
                iscontext: true
              right:
                value:
                  simple: image/png
              ignorecase: true
            - operator: isEqualString
              left:
                value:
                  simple: InfoFile.Info
                iscontext: true
              right:
                value:
                  simple: url.png
              ignorecase: true
          accessor: EntryID
          transformers:
          - operator: uniq
          - operator: FirstArrayElement
      execution-timeout:
        simple: "600"
      retry-count:
        simple: "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: 2b37321f-601a-412e-8057-655b0f99451f
    type: condition
    task:
      id: 2b37321f-601a-412e-8057-655b0f99451f
      version: -1
      name: Check Text
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "Yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: containsString
          left:
            value:
              complex:
                root: File
                accessor: Text
                transformers:
                - operator: toLowerCase
            iscontext: true
          right:
            value:
              simple: google search
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: Rasterize Test
fromversion: 5.0.0
description: ''
