name: Create DFIR Channel

on:
  pull_request:
    types:
      - labeled

jobs:

  is_mp_contrib:
    if: github.event.label.name == 'Contribution Form Filled'
    runs-on: ubuntu-latest
    steps:
    - name: Is PR Marketplace Contribution?
      id: get_is_mp_contrib
      run: |
        if [[ ${{ github.event.pull_request.title }} =~ "^[Marketplace Contribution]*" ]];then
            is_mp_contrib=true
        else
            is_mp_contrib=false

        echo is_mp_contrib=$is_mp_contrib

        echo "is_mp_contrib=$is_mp_contrib" >> "$GITHUB_OUTPUTS"
    outputs:
      is_mp_contrib: ${{ steps.get_is_mp_contrib.outputs.is_mp_contrib }}

  get_channel_members:
    if: github.event.label.name == 'Contribution Form Filled'
    runs-on: ubuntu-latest
    needs: is_mp_contrib
    steps:
    - name: Get Contributor GitHub Username
      id: get_contributor_gh_username
      run: |         
        if [[ ${{ needs.is_mp_contrib.outputs.is_mp_contrib }} == "true" ]];then 
          echo "Currently not supported."
          exit 0
        else
          contributor_gh_username=${{ github.event.pull_request.user.login }}
          echo "contributor_gh_username=$contributor_gh_username" >> "$GITHUB_OUTPUTS"
        fi

        echo contributor_gh_username=$contributor_gh_username
    outputs:
      contributor_gh_username: ${{ steps.get_contributor_gh_username.outputs.contributor_gh_username }}