variables:
  CURRENT_BRANCH_NAME: fix_rel_path_images_upload

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: fix_rel_path_images_upload
    project: "${CI_PROJECT_NAMESPACE}/infra"
