variables:
  CURRENT_BRANCH_NAME: add_playbook_failure_filtering

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: add_playbook_failure_filtering
    project: "${CI_PROJECT_NAMESPACE}/infra"
