variables:
  CURRENT_BRANCH_NAME: "CIAC-11068-playbook-tests-collector"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: "CIAC-11068-playbook-tests-collector"
    project: "${CI_PROJECT_NAMESPACE}/infra"
