variables:
  CURRENT_BRANCH_NAME: "testing_packs_upload_retry_platform_fix"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: $INFRA_BRANCH
    project: "${CI_PROJECT_NAMESPACE}/infra"
